### ISSUE TITLE
Profile added Readme

### ISSUE THREAD

**Issue by Mohiit70** [coding-connoisseurs-foet/Readme-Challenge#15]
![github com](https://github.com/coding-connoisseurs-foet/Readme-Challenge/assets/120316966/76e66998-1185-4f54-85c7-e0bf0b3c1ac1)

**Comment by Mohiit70** [comment]
> ![github com](https://user-images.githubusercontent.com/120316966/253769883-76e66998-1185-4f54-85c7-e0bf0b3c1ac1.png)

Profile added for ReadmeChallenge

**Comment by Priyanshi-Rai** [comment]
Raise a PR
