### ISSUE TITLE
Profile added readme

### ISSUE THREAD

**Issue by RicardoUValencia** [coding-connoisseurs-foet/Readme-Challenge#17]
![RicardoUValencia](https://github.com/coding-connoisseurs-foet/Readme-Challenge/assets/87098001/380ccf4d-8a77-47ff-8877-01866e4acb95)

**Comment by Priyanshi-Rai** [comment]
please raise a PR for this

**Comment by Priyanshi-Rai** [comment]
Good work, PR accepted
